assets: /mnt/home/fanxianzhe/LIBERO/libero/libero/./assets
bddl_files: /mnt/home/fanxianzhe/LIBERO/libero/libero/./bddl_files
benchmark_root: /mnt/home/fanxianzhe/LIBERO/libero/libero
init_states: /mnt/home/fanxianzhe/LIBERO/libero/libero/./init_files
